version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pixelvault-store-pixelvault_web_1
      APP_PORT: 3000

  web:
    image: pixelvault-store-pixelvault:0.5-beta
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - ENCRYPTION_KEY=${APP_SEED}
      - SESSION_SECRET=${APP_PASSWORD}
      - PORT=3000
      - DATA_DIR=/data
      - NODE_ENV=production
    ports:
      - "3769:3000"
